services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "9280:3000"
    volumes:
      - ./volumes:/var/lib/grafana
    networks:
      - home-sentry
    user: "1000:1000" # use current user, since we map settings to NAS
networks:
  home-sentry:
    name: home-sentry
    external: true

